//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team2B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookCode { get; set; }
        public string BookTitle { get; set; }
        public string BookGenere { get; set; }
        public string BookAuthor { get; set; }
        public short BookTotalCount { get; set; }
        public string BookPublisher { get; set; }
        public string BookEdition { get; set; }
        public short BookAvailableCount { get; set; }
    }
}
