//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team2B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int MemberID { get; set; }
        public string EmployeeID { get; set; }
        public int BookCode { get; set; }
        public System.DateTime DateIssue { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
        public string BookLoanStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual Transaction Transactions1 { get; set; }
        public virtual Transaction Transaction1 { get; set; }
        public virtual Transaction Transactions11 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
    }
}
